modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId="gravels_extended_battles"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="icon.png"
description='''${mod_description}'''

[[dependencies.gravels_extended_battles]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gravels_extended_battles]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"
#[[dependencies.gravels_extended_battles]]
#modId="cobblemon"
#mandatory=true
#versionRange="[1.5.2,)"
#ordering="NONE"
#side="BOTH"
[[dependencies.gravels_extended_battles]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.gravels_extended_battles]]
modId="midnightlib"
mandatory=true
versionRange="[1.6,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "gravels_extended_battles_common.mixins.json"
